package com.financeapp.core.ui.icons

/** Russian keyword synonyms per pickable icon, so the picker is searchable in Russian. */
val iconKeywordsRu: Map<String, String> = mapOf(
    "restaurant" to "еда ресторан кафе обед питание",
    "fastfood" to "фастфуд бургер еда перекус",
    "local_cafe" to "кофе кафе чай напиток",
    "local_bar" to "бар алкоголь пиво вино выпивка",
    "directions_car" to "машина авто автомобиль транспорт",
    "directions_bus" to "автобус транспорт проезд",
    "train" to "поезд электричка метро транспорт",
    "flight" to "самолёт полёт путешествие отпуск билет",
    "local_gas_station" to "бензин заправка топливо",
    "hotel" to "отель гостиница проживание",
    "fitness_center" to "спорт зал фитнес тренировка",
    "sports_esports" to "игры развлечения приставка",
    "movie" to "кино фильм развлечения",
    "music_note" to "музыка",
    "checkroom" to "одежда шоппинг гардероб",
    "phone" to "телефон связь мобильный",
    "phone_android" to "телефон android",
    "smartphone" to "смартфон телефон",
    "wifi" to "интернет вайфай связь",
    "laptop" to "ноутбук компьютер фриланс техника",
    "computer" to "компьюputer пк desktop",
    "home" to "дом жильё аренда квартплата коммуналка",
    "apartment" to "квартира жильё аренда",
    "bolt" to "электричество свет энергия",
    "water_drop" to "вода вода газ",
    "school" to "образование учёба школа университет",
    "work" to "работа зарплата офис",
    "business_center" to "бизнес офис работа",
    "trending_up" to "инвестиции рост акции доход",
    "account_balance" to "банк счёт вклад",
    "credit_card" to "карта кредит оплата",
    "savings" to "накопления копилка сбережения",
    "wallet" to "кошелёк деньги наличные",
    "payments" to "оплата платеж перевод",
    "card_giftcard" to "подарок сертификат",
    "redeem" to "подарок бонус награда",
    "celebration" to "праздник вечеринка",
    "pets" to "питомец животное кот собака",
    "favorite" to "любимое сердце",
    "local_hospital" to "больница госпиталь стационар",
    "local_pharmacy" to "аптека лекарства медикаменты",
    "medical_services" to "здоровье медицина врач аптека лекарства",
    "park" to "парк зона отдыха",
    "eco" to "экология природа зелень",
    "parking" to "парковка стоянка",
    "build" to "ремонт инструменты стройка",
    "brush" to "кисть рисование дизайн",
    "palette" to "палитра цвет дизайн",
    "folder" to "папка файл документ",
    "description" to "документ текст файл",
    "person" to "человек профиль",
    "group" to "группа люди",
    "notifications" to "уведомления напоминания",
    "flag" to "флаг метка",
    "label" to "метка ярлык",
    "analytics" to "аналитика статистика",
    "bar_chart" to "график диаграмма",
    "category" to "категория группа",
    "more_horiz" to "другое прочее ещё",
    "star" to "избранное звезда",
    "child_care" to "ребёнок дети детский",
)

/** True if [name] matches [query] by icon name substring OR any Russian keyword. Blank query matches all. */
fun iconMatches(name: String, query: String): Boolean {
    val q = query.trim().lowercase()
    if (q.isEmpty()) return true
    if (name.lowercase().contains(q)) return true
    return iconKeywordsRu[name]?.contains(q) == true
}
